GOL\RepositoriesBundle\Entity\mostRanked:
    type: entity
    table: null
    repositoryClass: GOL\RepositoriesBundle\Repository\mostRankedRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        repository:
            type: string
            length: 255
        author:
            type: string
            length: 255
        url:
            type: string
            length: 255
        description:
            type: string
            length: 255
        stars:
            type: string
            length: 255
    lifecycleCallbacks: {  }
