<?php

namespace GOL\RepositoriesBundle\Repository;

/**
 * mostRankedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mostRankedRepository extends \Doctrine\ORM\EntityRepository
{
}
