<?php

namespace GOL\RepositoriesBundle\Repository;

/**
 * mostCollaboratorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mostCollaboratorsRepository extends \Doctrine\ORM\EntityRepository
{
}
